management:
  security:
    enabled: false

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native
  application:
    name: spring-cloud-config-server
server:
  port: 8769
